-- MySQL Script generated by MySQL Workbench
-- Sat Apr 21 11:58:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema akbid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema akbid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `akbid` DEFAULT CHARACTER SET utf8 ;
USE `akbid` ;

-- -----------------------------------------------------
-- Table `akbid`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `akbid`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nomor_id` VARCHAR(45) NULL,
  `password` VARCHAR(150) NULL,
  `nama_lengkap` VARCHAR(60) NULL,
  `alamat` VARCHAR(150) NULL,
  `tanggal_lahir` VARCHAR(45) NULL,
  `jenis_kelamin` VARCHAR(45) NULL,
  `alamat_email` VARCHAR(45) NULL,
  `status_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `akbid`.`mahasiswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `akbid`.`mahasiswa` (
  `id_mahasiswa` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `jurusan` VARCHAR(45) NULL,
  `kelas` VARCHAR(45) NULL,
  `semester` VARCHAR(45) NULL,
  `status_pembayaran` VARCHAR(45) NULL,
  PRIMARY KEY (`id_mahasiswa`),
  INDEX `fk_mahasiswa_users_idx` (`id_user` ASC),
  CONSTRAINT `fk_mahasiswa_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `akbid`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `akbid`.`matakuliah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `akbid`.`matakuliah` (
  `id_matakuliah` INT NOT NULL AUTO_INCREMENT,
  `nama_matakuliah` VARCHAR(100) NULL,
  `kode_matakuliah` VARCHAR(45) NULL,
  `jumlah_sks` INT NULL,
  PRIMARY KEY (`id_matakuliah`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `akbid`.`nilai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `akbid`.`nilai` (
  `id_nilai` INT NOT NULL AUTO_INCREMENT,
  `id_matakuliah` INT NOT NULL,
  `id_mahasiswa` INT NOT NULL,
  `nilai` VARCHAR(45) NULL,
  `jenis_nilai` VARCHAR(45) NULL,
  `semester` VARCHAR(45) NULL,
  PRIMARY KEY (`id_nilai`),
  INDEX `fk_nilai_mahasiswa1_idx` (`id_mahasiswa` ASC),
  INDEX `fk_nilai_matakuliah1_idx` (`id_matakuliah` ASC),
  CONSTRAINT `fk_nilai_mahasiswa1`
    FOREIGN KEY (`id_mahasiswa`)
    REFERENCES `akbid`.`mahasiswa` (`id_mahasiswa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nilai_matakuliah1`
    FOREIGN KEY (`id_matakuliah`)
    REFERENCES `akbid`.`matakuliah` (`id_matakuliah`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `akbid`.`polling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `akbid`.`polling` (
  `id_polling` INT NOT NULL AUTO_INCREMENT,
  `nama_polling` VARCHAR(45) NULL,
  `jumlah_polling` VARCHAR(45) NULL,
  `persentase_poling` VARCHAR(45) NULL,
  PRIMARY KEY (`id_polling`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `akbid`.`dosen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `akbid`.`dosen` (
  `id_dosen` INT NOT NULL AUTO_INCREMENT,
  `nomor_induk` VARCHAR(45) NULL,
  `nama_lengkap` VARCHAR(45) NULL,
  `nip` VARCHAR(45) NULL,
  `gelar` VARCHAR(45) NULL,
  `jabatan_fungsional` VARCHAR(45) NULL,
  `alamat` VARCHAR(45) NULL,
  `tanggal_lahir` VARCHAR(45) NULL,
  PRIMARY KEY (`id_dosen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `akbid`.`penelitian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `akbid`.`penelitian` (
  `id_penelitian` INT NOT NULL AUTO_INCREMENT,
  `id_dosen` INT NOT NULL,
  `judul_penelitian` VARCHAR(150) NULL,
  PRIMARY KEY (`id_penelitian`),
  INDEX `fk_penelitian_dosen1_idx` (`id_dosen` ASC),
  CONSTRAINT `fk_penelitian_dosen1`
    FOREIGN KEY (`id_dosen`)
    REFERENCES `akbid`.`dosen` (`id_dosen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `akbid`.`pengabdian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `akbid`.`pengabdian` (
  `id_pengabdian` INT NOT NULL AUTO_INCREMENT,
  `id_dosen` INT NOT NULL,
  `judul_pengabdian` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pengabdian`),
  INDEX `fk_pengabdian_dosen1_idx` (`id_dosen` ASC),
  CONSTRAINT `fk_pengabdian_dosen1`
    FOREIGN KEY (`id_dosen`)
    REFERENCES `akbid`.`dosen` (`id_dosen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `akbid`.`kepegawaian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `akbid`.`kepegawaian` (
  `id_kepegawaian` INT NOT NULL AUTO_INCREMENT,
  `nip` VARCHAR(45) NULL,
  `jenis_kelamin` VARCHAR(45) NULL,
  `agama` VARCHAR(45) NULL,
  `tanggal_lahir` VARCHAR(45) NULL,
  `status_pegawai` VARCHAR(45) NULL,
  `alamat` VARCHAR(45) NULL,
  `nomor_tlp` VARCHAR(45) NULL,
  `jabatan` VARCHAR(45) NULL,
  PRIMARY KEY (`id_kepegawaian`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
